name: Backend CI/CD

on:
    push:
        branches: [ develop, master ]
        paths:
            - 'backend/**'
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'backend/**'
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        
        steps:
        -   uses: actions/checkout@v3

        -   name: Set up Go
            uses: actions/setup-go@v4
            with:
                go-version: '1.23.2'
                cache: true
                cache-dependency-path: backend/go.sum

        -   name: Install dependencies
            run: go mod download
        
        # -   name: Run tests
        #     run: go test -v ./...

        -   name: Get secrets from Azure Key Vault
            id: get-secrets
            uses: azure/keyvault@v1
            with:
                keyvault: devteamtestkv
                secrets: |
                    password

        -   name: Create env file
            working-directory: ./backend
            run: |
                cat << EOF > .env
                password=${{ steps.get-secrets.outputs.password }}
                SQLITE_HOT=${{ secrets.SQLITE_HOT }}
                SQLITE_PORT=${{ secrets.SQLITE_PORT }}
                SQLITE_USER=${{ secrets.SQLITE_USER }}
                SQLITE_PASSWORD=${{ secrets.SQLITE_PASSWORD }}
                SQLITE_DB_NAME=${{ secrets.SQLITE_DB_NAME }}
                SERVER_PORT=${{ secrets.SERVER_PORT }}
                SATELLITE_ISS=${{ secrets.SATELLITE_ISS }}
                SATELLITE_AUD=${{ secrets.SATELLITE_AUD }}
                SATELLITE_X5C=${{ secrets.SATELLITE_X5C }}
                SATELLITE_PRIVATE_KEY_PATH=${{ secrets.SATELLITE_PRIVATE_KEY_PATH }}
                SATELLITE_BASE_URL=${{ secrets.SATELLITE_BASE_URL }}
                EOF

        -   name: Build
            run: go build -o myapp ./cmd/...

        -   name: Copy files via ssh
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.AZURE_VM_IP }}
                username: ${{ secrets.AZURE_VM_USERNAME }}
                key: ${{ secrets.AZURE_VM_USERNAME }}
                source: "."
                target: "/home/${{ secrets.AZURE_VM_USERNAME }}"
    
        -   name: Execute commands on the server
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.AZURE_VM_IP }}
                username: ${{ secrets.AZURE_VM_USERNAME }}
                key: ${{ secrets.AZURE_VM_SSH_KEY }}
                script: |
                    cd /home/${{ secrets.AZURE_VM_USERNAME }}/backend
                    pm2 start myapp --name myapp
