name: Backend CI/CD

on:
    push:
        branches: [ develop, master ]
        paths:
            - 'backend/**'
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'backend/**'
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        
        steps:
        -   uses: actions/checkout@v3

        -   name: Set up Go
            uses: actions/setup-go@v4
            with:
                go-version: '1.23.2'
                cache: true
                cache-dependency-path: backend/go.sum

        -   name: Install dependencies
            run: go mod download
        
        # -   name: Run tests
        #     run: go test -v ./...

        -   name: Create env file
            working-directory: ./backend
            run: |
                cat << EOF > .env
                SQLITE_HOT=${{ secrets.SQLITE_HOT }}
                SQLITE_PORT=
                SQLITE_USER=user
                SQLITE_PASSWORD=
                SQLITE_DB_NAME=
                SERVER_PORT=${{ secrets.SERVER_PORT }}
                SATELLITE_ISS=${{ secrets.SATELLITE_ISS }}
                SATELLITE_AUD=EU.EORI.NLTESTPIRSAT1
                SATELLITE_X5C=MIIE9jCCA96gAwIBAgIIZ1RK4bvfZ6wwDQYJKoZIhvcNAQELBQAwPDE6MDgGA1UEAwwxVEVTVCBpU0hBUkUgRVUgSXNzdWluZyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBHNTAeFw0yMzA5MDkxMjI2NTJaFw0zMzA5MDYxMjI2NTFaMIGBMSQwIgYDVQQDDBtpU0hBUkUgVGVzdCBQSVIgU2F0ZWxsaXRlIDExHjAcBgNVBAUTFUVVLkVPUkkuTkxURVNUUElSU0FUMTEUMBIGA1UECwwLVGVzdCBhbmQgUUExFjAUBgNVBAoMDWlTSEFSRVRlc3RQSVIxCzAJBgNVBAYTAk5MMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAp2L3PjdLbKytSxywRQ9lyf4zHJGyXaLa3MBFcmd2S0kNISYlwhihJkEcxGeciF++UtYWkRQqtx3SgzVyxcnmrPsHGT4q1kHi76aV5WYmqMStUEK/YZ3Iov0e51UBWaiydM2k/cc0Bqx1iPaGXOBhGiau1/7wqCoFH407phI/pYlZ1DGe+B8QrB3Kf/Lv8tP+rsvY+rE1Y+HvlZJpTWjAU8d638LwQx116WsF1xRE8kdlbUdB4IpNOdj4K/WQa6WUwR6cUxJbbnJ81giVoNLxP3116L0zMGRULkBEP3x5LsggcKU64YmP0uFM3xFsETPWBsJEJzaSUXn2coVX0v1fn6sYygUFOZZXUwHzz5JnwDpoWwqPs877atlYCWpo3ZDXP0M04recUBopC/fCq3RQd8RYyHbGfKgx23gtONIhiFfNKzzh2PG6tWA8Jqz7Bmua9K3HglXIzqFl68aiBq4GpvxuQgmS5+ohOzzoBKMJoBbBWsiuD2bhI5Uw41hAlmdb6LlK71Jz+w0jwWxXoqQIaJjcTMNwE4sfFcSfojvODoxuWuKKZs+6xk2zmZYp4lpK2pVtUC2Uq+28gUugmMooTYkGcXvh0JNyDFKp2aqVXfd/K8581DbNMevcqAMwMmuwSRROvwnkvJPadiHAYpcoVOxOfVvNnFGoa96HoZ8e+O8CAwEAAaOBtTCBsjAfBgNVHSMEGDAWgBRtxWWJy9+RVNFrPLcCpS7NimiQHTAnBgNVHSUEIDAeBggrBgEFBQcDAgYIKwYBBQUHAwQGCCsGAQUFBwMBMDcGCCsGAQUFBwEDBCswKTAIBgYEAI5GAQEwCAYGBACORgEEMBMGBgQAjkYBBjAJBgcEAI5GAQYCMB0GA1UdDgQWBBTOxi/OaIiCNWdF8pVXsv4zUQXeOTAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBACQ3i28EOqp9h13hvqOQ1nTqi68dFWEvACHWv8aoNk8TupmiaN8i8Bfbp7JT2TmdlmO90FLu/EIC7Yrmi6QYagQf5EafQIIGQ1GpS6NM/PromzjD0RvyGPOdspcFHmXWw5PW1sPc/avxTWSqHCWc8R/yNYbNzxlkh/DQw97V3I0yMZxiidE3pw1oFp0CXsoWz4UkuOeEtOTYDANoWd+LsJkMudX2maARxAQiX9HQZqUTAIF41lXEz+Bq1YQRwKPO/BUKDfFJu+hbkifCZscJdRjQaUvEwUXnXB+ebSRoGQFzZYXrQXxbLTvlIayX/a2Pevp7fgzlCP6I6ZnSXu7pEy4=
                SATELLITE_PRIVATE_KEY_PATH=./keys/private-key.pem
                SATELLITE_BASE_URL=https://isharesat-mw.pir.test.ishareworks.nl
                EOF

        -   name: Build
            run: go build -o myapp ./cmd/...

        -   name: Copy files via ssh
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.AZURE_VM_IP }}
                username: ${{ secrets.AZURE_VM_USERNAME }}
                key: ${{ secrets.AZURE_VM_SSH_KEY }}
                source: "."
                target: "/home/${{ secrets.AZURE_VM_USERNAME }}"
    
        -   name: Execute commands on the server
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.AZURE_VM_IP }}
                username: ${{ secrets.AZURE_VM_USERNAME }}
                key: ${{ secrets.AZURE_VM_SSH_KEY }}
                script: |
                    cd /home/${{ secrets.AZURE_VM_USERNAME }}/backend
                    pm2 start myapp --name myapp
