name: Backend CI/CD

on:
    push:
        branches: [ develop, master ]
        paths:
            - 'backend/**'
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'backend/**'
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        
        steps:
        -   uses: actions/checkout@v3

        -   name: Set up Go
            uses: actions/setup-go@v4
            with:
                go-version: '1.23.2'
                cache: true
                cache-dependency-path: backend/go.sum

        -   name: Install dependencies
            run: go mod download
        
        # -   name: Run tests
        #     run: go test -v ./...

        -   name: Build
            run: go build -o myapp ./cmd/...

        -   name: Copy files via ssh
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.AZURE_VM_IP }}
                username: ${{ secrets.AZURE_VM_USERNAME }}
                key: ${{ secrets.AZURE_VM_SSH_KEY }}
                source: "."
                target: "/home/${{ secrets.AZURE_VM_USERNAME }}"
    
        -   name: Execute commands on the server
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.AZURE_VM_IP }}
                username: ${{ secrets.AZURE_VM_USERNAME }}
                key: ${{ secrets.AZURE_VM_SSH_KEY }}
                script: |
                    cd /home/${{ secrets.AZURE_VM_USERNAME }}/onboardingportal/backend
                    nohup ./myapp
